### ISSUE TITLE
【疑问】是否有办法指定下载所有架构的依赖

### ISSUE THREAD

**Issue by NepPure** [LowinLi/devpi-docker#1]
非常感谢大佬的这个项目，非常轻量方便。

现在遇到个问题，在mac上还原下载的，在离线windows上还是会缺少包，   
大部分依赖是按照操作系统和CPU架构有区分whl，不知大佬是否有更方便的解决方案？

另外我注意到这个项目用sqlite进行包索引管理，是否有从在线环境下载依赖增量迁移到离线环境的办法。目前我只能全量覆盖。

感谢！

**Comment by LowinLi** [comment]
1.第一个问题没有办法吧，因为很多pip包运行本身就是区分操作系统的，除非设置为any
2.第二个包索引管理，可以看一下devpi官方文档，看看能不能改造，[devpi](https://github.com/devpi/devpi)，我这个项目只是用docker包装了一层适合大陆的配置。

**Comment by NepPure** [comment]
谢谢！
